version: '3'

silent: true

vars:
  MAIN_MODULE: work.archaic.minau
  TEST_MODULE: work.archaic.minau.test
  LOG_MODULE: work.archaic.jules
  RELEASE_VERSION: 24
  EXAMPLE_MODULE: com.example.foo
  EXAMPLE_TEST_MODULE: com.example.foo.test

tasks:
  compile:
    desc: Compile the project
    cmds:
      - |
        rm -rf build/src
        javac \
          --module {{.MAIN_MODULE}} \
          --module-source-path src \
          --add-modules {{.LOG_MODULE}} \
          --module-path jar/bin \
          -d build/src \
          --release {{.RELEASE_VERSION}}

  lint:
    desc: Compile and lint the project
    cmds:
      - |
        rm -rf build/src
        javac \
          --module {{.MAIN_MODULE}} \
          --module-source-path src \
          --add-modules {{.LOG_MODULE}} \
          --module-path jar/bin \
          -d build/src \
          --release {{.RELEASE_VERSION}} \
          -Xdoclint:syntax,html,accessibility,reference \
          -Xlint:all \
          -Xdiags:verbose \
          -Xmaxerrs 200 \
          -Xmaxwarns 500

  run:
    desc: Run App for explorative testing
    deps: [compile]
    cmd: java --module-path build/src:jar/bin --add-modules work.archaic.lok -m {{.MAIN_MODULE}}/{{.MAIN_MODULE}}.Main

  test:
    desc: Build and test code using work.archaic.minau test runner
    cmds:
      - |
        rm -rf build/src
        javac \
          --module {{.TEST_MODULE}},{{.MAIN_MODULE}} \
          --module-source-path src \
          --add-modules {{.LOG_MODULE}} \
          --module-path jar/bin \
          -d build/src \
          --release {{.RELEASE_VERSION}}
        java -ea --module-path build/src:jar/bin \
          --add-modules {{.LOG_MODULE}},{{.TEST_MODULE}} \
          -m {{.MAIN_MODULE}}/{{.MAIN_MODULE}}.Main --output-dir out {{.TEST_MODULE}}

  test-example:
    desc: Build and test the example module using Minau
    cmds:
      - |
        rm -rf build/src
        javac \
          --module {{.EXAMPLE_MODULE}},{{.EXAMPLE_TEST_MODULE}},{{.MAIN_MODULE}} \
          --module-source-path src \
          --add-modules {{.LOG_MODULE}},work.archaic.service.catalog \
          --module-path jar/bin \
          -d build/src \
          --release {{.RELEASE_VERSION}}
        java -ea -Djava.util.logging.config.file=logging.properties \
          --module-path build/src:jar/bin \
          --add-modules {{.LOG_MODULE}},{{.EXAMPLE_TEST_MODULE}} \
          -m {{.MAIN_MODULE}}/{{.MAIN_MODULE}}.Main --output-dir build/src {{.EXAMPLE_TEST_MODULE}}

  format:
    desc: Format all Java source code using Google Java Format
    cmds:
      - |
        echo "Formatting Java source files..."
        find src -name "*.java" -exec java -jar tools/google-java-format-1.28.0-all-deps.jar --replace {} +
        echo "Code formatting complete"


